import { EmployeeLeave } from "../types";

export const mockEmployeeLeaveData: EmployeeLeave[] = [
  {
    employeeName: "Jenny Wilson",
    jobTitle: "Project Manager",
    avatar: "https://randomuser.me/api/portraits/women/21.jpg",
    timeOff: { total: 20, remaining: 15 },
    sickLeave: { total: 5, remaining: 4 },
    casualLeave: { total: 10, remaining: 8 },
    unpaidLeave: { total: 5, remaining: 3 },
    lastStatus: "Approved",
    leaveRequests: [
      {
        id: "req1",
        type: "Sick leave",
        requestedDate: "3/30/2025",
        status: "Approved",
        dates: "3/30/2025",
        duration: "1 day-8:00 work hours",
        note: "I need 1 day leave",
        adminNote: "Okay",
      },
      {
        id: "req2",
        type: "Casual leave",
        requestedDate: "3/30/2025",
        status: "Canceled",
        dates: "2/06/2025",
        duration: "1 day-8:00 work hours",
        note: "Personal day",
        adminNote: "I don't see any significant reason",
      },
    ],
  },
  {
    employeeName: "John Doe",
    jobTitle: "Software Engineer",
    avatar: "https://randomuser.me/api/portraits/men/32.jpg",
    timeOff: { total: 15, remaining: 10 },
    sickLeave: { total: 3, remaining: 0 },
    casualLeave: { total: 7, remaining: 5 },
    unpaidLeave: { total: 5, remaining: 5 },
    lastStatus: "Canceled",
    leaveRequests: [
      {
        id: "req3",
        type: "Unpaid leave",
        requestedDate: "4/15/2025",
        status: "Canceled",
        dates: "4/15/2025",
        duration: "2 days-16:00 work hours",
        note: "Family emergency",
        adminNote: "Needs more info",
      },
    ],
  },
  {
    employeeName: "Alice Smith",
    jobTitle: "UI/UX Designer",
    avatar: "https://randomuser.me/api/portraits/women/44.jpg",
    timeOff: { total: 18, remaining: 18 },
    sickLeave: { total: 4, remaining: 4 },
    casualLeave: { total: 9, remaining: 9 },
    unpaidLeave: { total: 5, remaining: 5 },
    lastStatus: "Approved",
    leaveRequests: [
      {
        id: "req4",
        type: "Casual leave",
        requestedDate: "5/01/2025",
        status: "Approved",
        dates: "5/01/2025",
        duration: "1 day-8:00 work hours",
        note: "Birthday",
        adminNote: "Enjoy!",
      },
    ],
  },
  {
    employeeName: "Mark Taylor",
    jobTitle: "QA Engineer",
    avatar: "https://randomuser.me/api/portraits/men/51.jpg",
    timeOff: { total: 12, remaining: 7 },
    sickLeave: { total: 4, remaining: 2 },
    casualLeave: { total: 6, remaining: 3 },
    unpaidLeave: { total: 2, remaining: 2 },
    lastStatus: "Approved",
    leaveRequests: [
      {
        id: "req5",
        type: "Sick leave",
        requestedDate: "6/10/2025",
        status: "Approved",
        dates: "6/11/2025 - 6/12/2025",
        duration: "2 days-16:00 work hours",
        note: "Fever and rest",
        adminNote: "",
      },
    ],
  },
  {
    employeeName: "Rachel Green",
    jobTitle: "HR Executive",
    avatar: "https://randomuser.me/api/portraits/women/68.jpg",
    timeOff: { total: 25, remaining: 20 },
    sickLeave: { total: 5, remaining: 5 },
    casualLeave: { total: 10, remaining: 8 },
    unpaidLeave: { total: 10, remaining: 7 },
    lastStatus: "Approved",
    leaveRequests: [
      {
        id: "req6",
        type: "Casual leave",
        requestedDate: "4/25/2025",
        status: "Approved",
        dates: "4/28/2025",
        duration: "1 day-8:00 work hours",
        note: "Wedding program",
        adminNote: "Approved",
      },
    ],
  },
  {
    employeeName: "Tom Hanks",
    jobTitle: "Backend Developer",
    avatar: "https://randomuser.me/api/portraits/men/11.jpg",
    timeOff: { total: 20, remaining: 11 },
    sickLeave: { total: 6, remaining: 2 },
    casualLeave: { total: 10, remaining: 6 },
    unpaidLeave: { total: 4, remaining: 3 },
    lastStatus: "Canceled",
    leaveRequests: [
      {
        id: "req7",
        type: "Sick leave",
        requestedDate: "5/15/2025",
        status: "Canceled",
        dates: "5/16/2025",
        duration: "1 day-8:00 work hours",
        note: "Medical checkup",
        adminNote: "Submit doctor's note",
      },
    ],
  },
  {
    employeeName: "Lily Adams",
    jobTitle: "Marketing Specialist",
    avatar: "https://randomuser.me/api/portraits/women/16.jpg",
    timeOff: { total: 16, remaining: 12 },
    sickLeave: { total: 4, remaining: 3 },
    casualLeave: { total: 8, remaining: 7 },
    unpaidLeave: { total: 4, remaining: 2 },
    lastStatus: "Approved",
    leaveRequests: [
      {
        id: "req8",
        type: "Unpaid leave",
        requestedDate: "6/01/2025",
        status: "Approved",
        dates: "6/05/2025 - 6/07/2025",
        duration: "3 days-24:00 work hours",
        note: "Traveling abroad",
        adminNote: "Safe journey",
      },
    ],
  },
];
